import type {Metadata} from "next";
import "./globals.css";
import Providers from "@/app/providers";
import React from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="ko">
        <body>
        <Providers>
            {children}
        </Providers>
        </body>
        </html>
    );
}
